name: Aws Deploy
description: Aws Deploy

inputs:
  CLOUD:
    required: true
    description: Aws Cloud
  ENV:
    required: true
    description: Aws Env
  REGION:
    required: true
    description: Aws Region

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
        role-to-assume: arn:aws:iam::${{ inputs.ACCOUNT_ID }}:role/${{ inputs.ENV }}-access
        role-duration-seconds: 3600
        role-session-name: github

    - name: AWS Setup
      shell: bash
      id: aws-setup
      run: |
        mv terragrunt.aws.hcl terragrunt.hcl

    - name: Build
      shell: bash
      id: terragrunt-plan
      working-directory: ${{ inputs.CLOUD }}/${{ inputs.REGION }}/${{ inputs.ENV }}/
      run: |
        terragrunt run-all plan -no-color --terragrunt-non-interactive --terragrunt-include-external-dependencies | tee plan-${{ inputs.ENV }}.txt

    - uses: actions/upload-artifact@v3
      with:
        name: terragrunt
        path: ${{ inputs.CLOUD }}/${{ inputs.REGION }}/${{ inputs.ENV }}/plan-${{ inputs.ENV }}.txt
