name: Plan
on:
  workflow_call:
    inputs:
      CLOUD:
        required: true
        type: string
      ENV:
        required: true
        type: string

steps:
  - id: 'auth'
    uses: 'google-github-actions/auth@v2'
    with:
      workload_identity_provider: 'projects/${{ secrets.PROJECT_ID }}/locations/global/workloadIdentityPools/${{ secrets.POOL }}/providers/${{ secrets.PROVIDER }}'
      service_account: '${{ secrets.SERVICE_ACCOUNT }}'

  - name: 'Set up Cloud SDK'
    uses: 'google-github-actions/setup-gcloud@v2'
    with:
      version: '>= 363.0.0'

  - name: 'Use gcloud CLI'
    run: 'gcloud info'

  - name: GCP Setup
    id: gcp-setup
    run: |
      mv terragrunt.gcp.hcl terragrunt.hcl

  - name: Plan
    id: terragrunt-plan
    working-directory: ${{ inputs.CLOUD }}/${{ inputs.REGION }}/${{ inputs.ENV }}/
    run: |
      terragrunt run-all init
      terragrunt run-all plan -no-color --terragrunt-non-interactive --terragrunt-include-external-dependencies | tee plan-${{ inputs.CLOUD }}${{ inputs.REGION }}-${{ inputs.ENV }}.txt

  - uses: actions/upload-artifact@v3
    with:
      name: terragrunt
      path: ${{ inputs.CLOUD }}/${{ inputs.REGION }}/${{ inputs.ENV }}/plan-${{ inputs.ENV }}.txt
