name: Plan
on:
  workflow_call:
    inputs:
      CLOUD:
        required: true
        type: string
      ENV:
        required: true
        type: string

steps:
  - name: Checkout
    uses: actions/checkout@v3

  - name: Azure Setup
    id: azure-setup
    run: |
      mv terragrunt.azure.hcl terragrunt.hcl

  - name: Plan
    id: terragrunt-plan
    working-directory: ${{ inputs.CLOUD }}/${{ inputs.REGION }}/${{ inputs.ENV }}/
    run: |
      terragrunt run-all init
      terragrunt run-all plan -no-color --terragrunt-non-interactive --terragrunt-include-external-dependencies | tee plan-${{ inputs.ENV }}.txt

  - uses: actions/upload-artifact@v3
    with:
      name: terragrunt
      path: ${{ inputs.CLOUD }}/${{ inputs.REGION }}/${{ inputs.ENV }}/plan-${{ inputs.ENV }}.txt
