name: Plan
on:
  workflow_call:
    inputs:
      CLOUD:
        required: true
        type: string
      ENV:
        required: true
        type: string

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    container: ghcr.io/TheDao032/terragrunt-environments
    environment:
      name: ${{ inputs.ENV }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
      #     aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      #     role-to-assume: arn:aws:iam::${{ inputs.ACCOUNT_ID }}:role/DevAccess
      #     role-duration-seconds: 3600
      #     role-session-name: github

      - name: Azure Setup
        id: azure-setup
        run: |
          mv terragrunt.azure.hcl terragrunt.hcl

      - name: Plan
        id: terragrunt-plan
        working-directory: ${{ inputs.CLOUD }}/${{ inputs.REGION }}/${{ inputs.ENV }}/
        run: |
          terragrunt run-all init
          terragrunt run-all plan -no-color --terragrunt-non-interactive --terragrunt-include-external-dependencies | tee plan-${{ inputs.ENV }}.txt

      - uses: actions/upload-artifact@v3
        with:
          name: terragrunt
          path: ${{ inputs.CLOUD }}/${{ inputs.REGION }}/${{ inputs.ENV }}/plan-${{ inputs.ENV }}.txt
