name: Root pipeline

on:
  push:
    branches:
      - dev
      - uat
      - prod
      # - main
    tags:
      - "*"

defaults:
  run:
    shell: bash

env:
  IMAGE_NAME: ${{ github.repository }}
  ENV_NAME: ${{ github.ref_name }}
  CLOUD_ACTION: "gcp"
  CLOUD_NAME: "google-cloud-platform"

jobs:
  plan:
    name: Plan infrastructure
    runs-on: ubuntu-latest
    container: ${{ vars.REGISTRY }}/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Plan GCP infrastructure
        uses: ./.github/actions/gcp/build
        with:
          CLOUD: "${{ env.CLOUD_NAME }}"
          ENV: "${{ env.ENV_NAME }}"
